version: '3.8'

services:
  server:
    build:
      context: ./server  # Assuming the server is in the ./server directory
    ports:
      - "5001:5000"  # Expose port 5000 for the backend
    environment:
      - MONGO_URI=mongodb://mongo:27017/your-db  # Set environment variable for MongoDB connection
    depends_on:
      - mongo  # Ensure mongo service is started before the backend

  frontend:
    build:
      context: ./zynk  # Assuming the frontend is in the ./zynk directory
    ports:
      - "3001:3000"  # Expose port 3001 for the frontend (React app)
    depends_on:
      - server  # Ensure server is started before the frontend

  mongo:
    image: mongo:5  # Use official MongoDB image
    container_name: mongodb  # Set container name
    ports:
      - "27017:27017"  # Expose MongoDB default port
    volumes:
      - mongo_data:/data/db  # Persist MongoDB data

volumes:
  mongo_data:  # Define a named volume for MongoDB data persistence
